version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
      - ./backend/db.sqlite:/app/db.sqlite
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3000  # For browser requests
      - BACKEND_URL=http://backend:3000  # For server-side requests
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge